ver = "1.0.0"

[server]
username = "root"
passwd = "taosdata"
ip = "192.168.1.119:0"
proto = "@/tcp"
sql = "taosSql"

[taos]
database = "globaldb"
table = "h4_5103_spx"
stable = "stock_4h"
word = "where date = 20191010"